IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_Name = 'Message'))
BEGIN
	CREATE TABLE [dbo].[Message](
		[Id] [bigint] IDENTITY(1,1) NOT NULL,
		[SenderId] [bigint] FOREIGN KEY REFERENCES [dbo].[User](Id),
		[ReceiverId] [bigint] FOREIGN KEY REFERENCES [dbo].[User](Id),
		[Content] varchar(max) NOT NULL,
		[TimeStamp] DATETIME DEFAULT GETDATE(),
		[IsRead] BIT DEFAULT 0,
		CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED 
		(
			   [Id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	);
END