IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_Name = 'Subject'))
BEGIN
	CREATE TABLE [dbo].[Subject](
		[Id] [bigint] IDENTITY(1,1) NOT NULL,
		[ProgramId] int NOT NULL,
		[Name] varchar(100) NOT NULL
		CONSTRAINT [PK_Subject] PRIMARY KEY CLUSTERED 
		(
			   [Id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	);
END