// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.Models.Entity
{
    public partial class Chat
    {
        public Chat()
        {
            Messages = new HashSet<Message>();
        }

        public long Id { get; set; }
        public long? User1 { get; set; }
        public long? User2 { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }

        public virtual User? User1Navigation { get; set; }
        public virtual User? User2Navigation { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}