// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.ImplementationsDAL.PMFWikipedia.Models;

public partial class FavoriteSubject
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public long SubjectId { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual User User { get; set; }
}