// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.Models.Entity
{
    public partial class KolokvijumResenje
    {
        public long Id { get; set; }
        public string FilePath { get; set; } = null!;
        public long AuthorId { get; set; }
        public long KolokvijumId { get; set; }
        public long SubjectId { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }

        public virtual User Author { get; set; } = null!;
        public virtual Kolokvijum Kolokvijum { get; set; } = null!;
        public virtual Subject Subject { get; set; } = null!;
    }
}