// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.Models.Entity
{
    public partial class Message
    {
        public long Id { get; set; }
        public long? SenderId { get; set; }
        public long? ReceiverId { get; set; }
        public string Content { get; set; } = null!;
        public DateTime? TimeStamp { get; set; }
        public bool? IsRead { get; set; }

        public virtual User? Receiver { get; set; }
        public virtual User? Sender { get; set; }
    }
}