// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.Models.Entity
{
    public partial class Notification
    {
        public long Id { get; set; }
        public long Author { get; set; }
        public long Subject { get; set; }
        public long Post { get; set; }
        public long Receiver { get; set; }
        public int NotificationId { get; set; }
        public bool IsRead { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }

        public virtual User AuthorNavigation { get; set; } = null!;
        public virtual Post PostNavigation { get; set; } = null!;
        public virtual User ReceiverNavigation { get; set; } = null!;
        public virtual Subject SubjectNavigation { get; set; } = null!;
    }
}