// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.Models.Entity
{
    public partial class Post
    {
        public long Id { get; set; }
        public string Title { get; set; } = null!;
        public string Content { get; set; } = null!;
        public long? Author { get; set; }
        public long? LastEditedBy { get; set; }
        public long? Subject { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }

        public virtual User? AuthorNavigation { get; set; }
        public virtual User? LastEditedByNavigation { get; set; }
        public virtual Subject? SubjectNavigation { get; set; }
    }
}