// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.ImplementationsDAL.PMFWikipedia.Models;

public partial class Subject
{
    public long Id { get; set; }

    public int ProgramId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<FavoriteSubject> FavoriteSubjects { get; set; } = new List<FavoriteSubject>();
}