// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.Models.Entity
{
    public partial class Subject
    {
        public Subject()
        {
            EditedPosts = new HashSet<EditedPost>();
            FavoriteSubjects = new HashSet<FavoriteSubject>();
            IspitResenjes = new HashSet<IspitResenje>();
            Ispits = new HashSet<Ispit>();
            KolokvijumResenjes = new HashSet<KolokvijumResenje>();
            Kolokvijums = new HashSet<Kolokvijum>();
            Notifications = new HashSet<Notification>();
            Posts = new HashSet<Post>();
        }

        public long Id { get; set; }
        public int ProgramId { get; set; }
        public string Name { get; set; } = null!;
        public int Year { get; set; }
        public int Semester { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public long? LastModifiedBy { get; set; }

        public virtual ICollection<EditedPost> EditedPosts { get; set; }
        public virtual ICollection<FavoriteSubject> FavoriteSubjects { get; set; }
        public virtual ICollection<IspitResenje> IspitResenjes { get; set; }
        public virtual ICollection<Ispit> Ispits { get; set; }
        public virtual ICollection<KolokvijumResenje> KolokvijumResenjes { get; set; }
        public virtual ICollection<Kolokvijum> Kolokvijums { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}