// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.Models.Entity
{
    public partial class Subject
    {
        public Subject()
        {
            FavoriteSubjects = new HashSet<FavoriteSubject>();
            Notifications = new HashSet<Notification>();
            Posts = new HashSet<Post>();
        }

        public long Id { get; set; }
        public int ProgramId { get; set; }
        public string Name { get; set; } = null!;
        public int Year { get; set; }
        public int Semester { get; set; }

        public virtual ICollection<FavoriteSubject> FavoriteSubjects { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}