// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMFWikipedia.ImplementationsDAL.PMFWikipedia.Models;

public partial class User
{
    public long Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int Program { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime DateModified { get; set; }

    public long LastModifiedBy { get; set; }

    public bool Verified { get; set; }

    public string RegisterToken { get; set; }

    public DateTime RegisterTokenExpirationTime { get; set; }

    public string ResetToken { get; set; }

    public DateTime? ResetTokenExpirationTime { get; set; }

    public string PhotoPath { get; set; }

    public virtual ICollection<FavoriteSubject> FavoriteSubjects { get; set; } = new List<FavoriteSubject>();
}